== Config_Lite

=== Description

a simple, lightweight and fast class for ini style configuration files, 
with the native PHP function `parse_ini_file' under the hood.
 +
Config_Lite is inspired by Pythons ConfigParser. +
 +
A "Config_Lite" file consists of sections, "[section]", 
followed by "name = value" (KVP) entries.


=== Examples

.A simple configuration file: `test.ini'
----------

public_key_file =  "~/.ssh/id_rsa.pub"
debug = yes

[general]
lang = "en"

[db]
user = "dionysis"
password = "c2oiVnY!f8sf"

----------

.Read Configuration file:
----------
<?php

require_once 'Config/Lite.php';

$config = new Config_Lite('test.ini');

echo $config->get('db', 'user'); // dionysis
echo $config->get(null, 'public_key_file'); // ~/.ssh/id_rsa.pub

if (true === $config->getBool(null, 'debug', true)) {
	echo $config;
}

// read with ArrayAccess
echo $config['db']['password']; // c2oiVnY!f8sf

----------



.Save Configuration file:
----------
$config->set('db', 'user', 'JohnDoe')
	->set('db', 'password', 'd0g1tcVs$HgIn1');

// set with ArrayAccess
$config['public_key_file'] = '~/.ssh/id_rsa.pub';
$config['general'] = array('lang' => 'de');

// save object to file
$config->save();
----------


.Create configuration file:
----------
<?php

require_once 'Config/Lite.php';

$config = new Config_Lite();
$config->set('db', 'user', 'JohnDoe')
	->set('db', 'password', 'd0g1tcVs$HgIn1');

// set global value 'debug' as bool
$config->setBool(null, 'debug', false);

// save object to file
$config->save();
----------


.Alternative file creation with write:
----------
<?php

require_once 'Config/Lite.php';

$config = new Config_Lite();
$config->write('test.ini', array(
			'public_key_file' =>  "~/.ssh/id_rsa.pub",
			'general' => array(
				'lang' => 'fr'
			),
			'db' => array(
				'user' => 'dionysis',
				'password' => 'd0g1tcVs$HgIn1'
			)
		);

----------


.global Configuration options (without sections) :
----------
$config->set(null, 'private_key_file', '~/.ssh/id_rsa');
// set with arrayaccess
$config['public_key_file'] = '~/.ssh/id_rsa.pub';

$config->sync();

echo $config->get(null, 'public_key_file');
// get with arrayaccess
echo $config['private_key_file'];
----------

=== Notes & Limitations

Config_Lite is an OO frontend to `parse_ini_file' and writing ini files, +
but you can also use the public method `write' if you only want to write an array as ini file. +
Use getString and setString to save and read Strings with double _and_ single-quotes. +
Use getBool if you need a real bool type, eg. for strict equality comparision. +
No support of comments and multiline strings, because reading with `parse_ini_file' does not support it.
File locking is not part of this Class +


=== Contributing

Patches are Welcome! +
Create an Issue with a Link to your forked branch.

https://github.com/pce/config_lite +
http://pear.php.net/pepr/pepr-proposal-show.php?id=645
